// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppForTestAspDotNetCoreMVC.DBContextAndEntities;

namespace WebAppForTestAspDotNetCoreMVC.Migrations
{
    [DbContext(typeof(CDPreActivationDbContext))]
    [Migration("20210127055350_InitMigration")]
    partial class InitMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {

        }
    }
}
